/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.AuthorModel;
import entity.Authors;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import entity.Dao;

/**
 *
 * @author nnd2890
 */
public class AuthorViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    // Initialize localDate veriable
    private DateFormat dtf;
    private Date localDate;

    public AuthorViewPanel() {
        initComponents();
        showList();
    }
    
    // Show list of authors into table
    public void showList() {
        ArrayList<Authors> list = AuthorModel.listAuthor();
        DefaultTableModel model = (DefaultTableModel) jTableAuthor.getModel();
        model.setRowCount(0);
        for (Authors author : list) {
            Object[] row = {author.getId()
                    , author.getName()
                    , author.getDescription()
                    , author.getCreated_at()
                    , author.getUpdated_at()
                    , author.getStatus()};
            model.addRow(row);
        }
    }
    
    // Reset
    public void resetFuntion() {
        jTextField_id.setText("");
        JTextField_name.setText("");
        jTextArea_description.setText("");
        jTextField_createdDate.setText("");
        jTextField_updatedDate.setText("");
        jTextField_status.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTextField_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAuthor = new javax.swing.JTable();
        jButton_insert = new javax.swing.JButton();
        jButton_Udate = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_createdDate = new javax.swing.JTextField();
        jTextField_updatedDate = new javax.swing.JTextField();
        jTextField_status = new javax.swing.JTextField();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 500));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Author's name");

        jLabel2.setText("Description");

        jTableAuthor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Author's name", "Description", "Created date", "Updated date", "Status"
            }
        ));
        jTableAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAuthorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAuthor);

        jButton_insert.setBackground(new java.awt.Color(0, 153, 153));
        jButton_insert.setForeground(new java.awt.Color(255, 255, 255));
        jButton_insert.setText("Insert");
        jButton_insert.setToolTipText("");
        jButton_insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_insertMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_insertMousePressed(evt);
            }
        });
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });

        jButton_Udate.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Udate.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Udate.setText("Update");
        jButton_Udate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UdateActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(0, 153, 153));
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_reset.setBackground(new java.awt.Color(0, 153, 153));
        jButton_reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reset.setText("Resest");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jTextArea_description.setColumns(20);
        jTextArea_description.setFont(new java.awt.Font("VNI-Times", 0, 13)); // NOI18N
        jTextArea_description.setRows(5);
        jScrollPane2.setViewportView(jTextArea_description);

        jLabel3.setText("Id");

        jLabel5.setText("Created date");

        jLabel4.setText("Updated Date");

        jLabel6.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(JTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField_createdDate)
                                                .addComponent(jTextField_updatedDate)
                                                .addComponent(jTextField_status, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel3)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Udate, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jButton_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_insert)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Udate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_delete)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_reset)))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_createdDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_updatedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UdateActionPerformed
        // Update
        int id = Integer.parseInt(jTextField_id.getText());
        String name = JTextField_name.getText();
        String description = jTextArea_description.getText();
        Authors au = new Authors();
        au.setId(id);
        au.setName(name);
        au.setDescription(description);
        try {
            AuthorModel.updateAuthor(au);
            JOptionPane.showMessageDialog(null, "Successful!");
            showList();
            resetFuntion();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_UdateActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        resetFuntion();
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        // Insert Authors
        String name = JTextField_name.getText();
        String description = jTextArea_description.getText();
        Authors au = new Authors();
        au.setName(name);
        au.setDescription(description);
        try {
            AuthorModel.insertAuthors(au);
            JOptionPane.showMessageDialog(null, "Successful!");
            showList();
            resetFuntion();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jTableAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAuthorMouseClicked
        // Display selected row into JTextField
        int i = jTableAuthor.getSelectedRow();
        TableModel model = jTableAuthor.getModel();
        jTextField_id.setText(model.getValueAt(i, 0).toString());
        JTextField_name.setText(model.getValueAt(i, 1).toString());
        jTextArea_description.setText(model.getValueAt(i, 2).toString());
        jTextField_createdDate.setText(model.getValueAt(i, 3).toString());
        jTextField_updatedDate.setText(model.getValueAt(i, 4).toString());
        jTextField_status.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTableAuthorMouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // Delete
        try {
            int id = Integer.parseInt(jTextField_id.getText());
            Authors au = new Authors();
            au.setId(id);
            AuthorModel.deleteAuthor(au);
            JOptionPane.showMessageDialog(null, "Successful!");
            DefaultTableModel model = (DefaultTableModel) jTableAuthor.getModel();
            model.setRowCount(0);
            showList();
            resetFuntion();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_insertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_insertMouseClicked
        
    }//GEN-LAST:event_jButton_insertMouseClicked

    private void jButton_insertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_insertMousePressed
        
    }//GEN-LAST:event_jButton_insertMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField_name;
    private javax.swing.JButton jButton_Udate;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAuthor;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextField jTextField_createdDate;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_status;
    private javax.swing.JTextField jTextField_updatedDate;
    // End of variables declaration//GEN-END:variables
}
