/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nnd2890
 */
public class MenuViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuViewJPanel
     */
    
    private AuthorViewPanel au = new AuthorViewPanel();
    private CategoriesViewPanel ca = new CategoriesViewPanel();
    public MenuViewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_book = new javax.swing.JButton();
        jButton_author = new javax.swing.JButton();
        jButton_catagory = new javax.swing.JButton();

        jButton_book.setText("Book");
        jButton_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookActionPerformed(evt);
            }
        });

        jButton_author.setText("Author");
        jButton_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_authorActionPerformed(evt);
            }
        });

        jButton_catagory.setText("Catagory");
        jButton_catagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_catagoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton_book)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_author)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_catagory)
                .addContainerGap(626, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_book)
                .addComponent(jButton_author)
                .addComponent(jButton_catagory))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookActionPerformed
        
    }//GEN-LAST:event_jButton_bookActionPerformed

    private void jButton_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_authorActionPerformed
        au = new AuthorViewPanel();
        ca = new CategoriesViewPanel();
        au.setVisible(true);
        ca.setVisible(false);
    }//GEN-LAST:event_jButton_authorActionPerformed

    private void jButton_catagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_catagoryActionPerformed
        au = new AuthorViewPanel();
        ca = new CategoriesViewPanel();
        au.setVisible(false);
        ca.setVisible(true);
    }//GEN-LAST:event_jButton_catagoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_author;
    private javax.swing.JButton jButton_book;
    private javax.swing.JButton jButton_catagory;
    // End of variables declaration//GEN-END:variables
}
